'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var AVATARCHECKBOX = exports.AVATARCHECKBOX = 'AvatarCheckbox';
var AVATAR_OVERLAY = exports.AVATAR_OVERLAY = 'AvatarOverlay';
var BANNER = exports.BANNER = 'Banner';
var BOTTOMSHEET = exports.BOTTOMSHEET = 'BottomSheet';
var BOTTOMSHEET_PLUS = exports.BOTTOMSHEET_PLUS = 'BottomSheetPlus';
var BOX_HEADER = exports.BOX_HEADER = 'BoxHeader';
var BUTTON_GROUP = exports.BUTTON_GROUP = 'ButtonGroup';
var CARDACTIONSRIGHT = exports.CARDACTIONSRIGHT = 'CardActionsRight';
var CARDACTIONSSPACED = exports.CARDACTIONSSPACED = 'CardActionsSpaced';
var CARDTITLEBUTTONS = exports.CARDTITLEBUTTONS = 'CardTitleButtons';
var CARD_EXPANDABLE = exports.CARD_EXPANDABLE = 'CardExpandable';
var CARD_PRIMARY = exports.CARD_PRIMARY = 'CardPrimary';
var DIALOGWITHIMAGE = exports.DIALOGWITHIMAGE = 'DialogWithImage';
var DIALOG_LAYOUT = exports.DIALOG_LAYOUT = 'DialogLayout';
var DISABLED_INPUT = exports.DISABLED_INPUT = 'DisabledInput';
var DROPDOWNPLUS = exports.DROPDOWNPLUS = 'DropdownPlus';
var FLEXLIST = exports.FLEXLIST = 'FlexList';
var FOOTER = exports.FOOTER = 'Footer';
var GROUPLISTDIVIDER = exports.GROUPLISTDIVIDER = 'GroupListDivider';
var GROUPLISTITEM = exports.GROUPLISTITEM = 'GroupListItem';
var HOVERABLECONTENT = exports.HOVERABLECONTENT = 'HoverableContent';
var ICONSWITCHER = exports.ICONSWITCHER = 'IconSwitcher';
var INPUTGROUP = exports.INPUTGROUP = 'InputGroup';
var MESSAGEITEM = exports.MESSAGEITEM = 'MessageItem';
var NAVDRAWER_PLUS = exports.NAVDRAWER_PLUS = 'NavDrawerPlus';
var NAVIGATIONS_CHIPS = exports.NAVIGATIONS_CHIPS = 'NavigationChips';
var RED_HEADING = exports.RED_HEADING = 'RedHeading';
var SHADOW_BOX = exports.SHADOW_BOX = 'shadowBox';
var SIDEBAR_PLUS = exports.SIDEBAR_PLUS = 'NavDrawerPlus';
var STATUSAVATAR = exports.STATUSAVATAR = 'StatusAvatar';
var STEPSLIST = exports.STEPSLIST = 'StepsList';
var STYLEDAVATAR = exports.STYLEDAVATAR = 'StyledAvatar';
var STYLEDLISTITEM = exports.STYLEDLISTITEM = 'StyledListItem';
var STYLED_DROPDOWN = exports.STYLED_DROPDOWN = 'StyledDropdown';
var STYLED_INPUT = exports.STYLED_INPUT = 'StyledInput';
var TRANSPARENT_CHIP = exports.TRANSPARENT_CHIP = 'TransparentChip';
var UPLOAD = exports.UPLOAD = 'UploadZone';
var UPLOAD_BUTTON = exports.UPLOAD_BUTTON = 'UploadButton';
var VERTICALDIVIDER = exports.VERTICALDIVIDER = 'VerticalDivider';
var VIDEOPANEL = exports.VIDEOPANEL = 'VideoPanel';
var NAVDRAWER_PLUS_CHILDREN = exports.NAVDRAWER_PLUS_CHILDREN = 'NavDrawerPlusChildren';
var CHAT_CONTENT = exports.CHAT_CONTENT = 'ChatContent';