import {themr} from 'react-css-themr';
import {ICONSWITCHER, BUTTON_SWITCHER} from '../identifiers';
import theme from './theme.scss';
import {IconSwitcherFactory} from './IconSwitcher';
import {ButtonSwitcherFactory} from './ButtonSwitcher';
const IconSwitcher = IconSwitcherFactory();
const ButtonSwitcher = ButtonSwitcherFactory();
const ThemedIconSwitcher = themr(ICONSWITCHER, theme)(IconSwitcher);
const ThemedButtonSwitcher = themr(BUTTON_SWITCHER, theme)(ButtonSwitcher);
export {ThemedIconSwitcher as IconSwitcher};
export {ThemedButtonSwitcher as ButtonSwitcher};
